"""
Step 9 — Post-processing quality checks (video-file-based).

Checks verify that the output .mp4 was actually written and is readable,
and that it contains at least `min_active_frames` frames.

A global dataset report is generated by reading the shared metadata.json
and cross-referencing each entry against the output video files.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import List

import cv2

from .storage import _load_global_metadata


@dataclass
class SampleReport:
    label: str
    video_name: str  # original stem (no extension)
    passed: bool
    warnings: List[str] = field(default_factory=list)
    # filled from metadata if available
    trimmed_frames: int = 0
    output_frames: int = 0


def check_sample(
    output_dir: Path,
    label: str,
    video_name: str,
    min_frames: int = 10,
) -> SampleReport:
    """
    Verify a single processed video.

    Checks:
    1. Output .mp4 file exists.
    2. cv2 can open the file.
    3. Frame count reported by cv2 >= min_frames.
    """
    stem = Path(video_name).stem
    video_path = output_dir / label / f"{stem}.mp4"
    report = SampleReport(label=label, video_name=stem, passed=True)

    if not video_path.exists():
        report.passed = False
        report.warnings.append(f"Output file not found: {video_path}")
        return report

    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        report.passed = False
        report.warnings.append(f"cv2 cannot open file: {video_path}")
        cap.release()
        return report

    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    cap.release()

    report.output_frames = frame_count

    if frame_count < min_frames:
        report.passed = False
        report.warnings.append(f"Too few frames: {frame_count} < required {min_frames}")

    # Pull trimmed_frames from global metadata if present
    meta = _load_global_metadata(output_dir)
    video_meta = meta.get(label, {}).get(stem, {})
    report.trimmed_frames = video_meta.get("trimmed_frame_count", 0)

    return report


def generate_dataset_report(output_dir: Path) -> List[SampleReport]:
    """
    Check every video recorded in metadata.json.

    Returns a list of SampleReport objects (one per metadata entry).
    Videos listed in metadata but whose file is missing will fail.
    """
    meta = _load_global_metadata(output_dir)
    reports: List[SampleReport] = []

    for label, videos in meta.items():
        for stem, video_meta in videos.items():
            min_frames = 10
            report = check_sample(output_dir, label, stem, min_frames)
            report.trimmed_frames = video_meta.get("trimmed_frame_count", 0)
            reports.append(report)

    return reports
